apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: config-default
  namespace: default
spec:
  timeoutSec: 900
  iap:
    enabled: true
    oauthclientCredentials:
      secretName: iap-secret