apiVersion: apps/v1
kind: Deployment
metadata:
  name: stable-diffusion-nginx-deployment
  labels:
    app: stable-diffusion-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stable-diffusion-nginx
  template:
    metadata:
      labels:
        app: stable-diffusion-nginx
    spec:
      containers:
      - name: stable-diffusion-nginx
        image: $NGINX_IMAGE
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool
