apiVersion: "agones.dev/v1"
kind: Fleet
metadata:
  name: sd-agones-fleet
spec:
  replicas: 1
  template:
    spec:
      container: sd-sidecar
      ports:
      - name: default
        container: sd-sidecar
        containerPort: 7654
      - name: sd
        container: stable-diffusion-webui
        containerPort: 7860
        protocol: TCP
      template:
        spec:
          containers:
          - name: sd-sidecar
            image: $AGONES_SIDECAR_IMAGE
            resources:
              requests:
                memory: "256Mi"
                cpu: "200m"
              limits:
                memory: "256Mi"
                cpu: "200m"
          - name: stable-diffusion-webui
            image: $SD_WEBUI_IMAGE
            imagePullPolicy: Always
            livenessProbe:
              httpGet:
                path: /docs
                port: 7860
              initialDelaySeconds: 60
              periodSeconds: 3
            command: ["/bin/sh", "start.sh"]
            volumeMounts:
            - mountPath: /sd_dir
              name: stable-diffusion-storage
            - mountPath: /stable-diffusion-webui/models/Lora
              name: stable-diffusion-storage
              subPath: models/Lora
            - mountPath: /stable-diffusion-webui/models/Stable-diffusion
              name: stable-diffusion-storage
              subPath: models/Stable-diffusion
            resources:
              limits:
                nvidia.com/gpu: 1
          volumes:
            - name: stable-diffusion-storage
              persistentVolumeClaim:
                claimName: vol1
