apiVersion: v1
kind: PersistentVolume
metadata:
  name: filestore-nfs-pv
spec:
  capacity:
    storage: 1Ti
  accessModes:
  - ReadWriteMany
  nfs:
    path: /$FILESHARE_NAME
    server: $FILESTORE_IP

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: vol1
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: ""
  volumeName: filestore-nfs-pv
  resources:
    requests:
      storage: 1Ti
